version: '3.8'

services:
  server:
    container_name: jesus-server-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/jesus_db
      JWT_SECRET: asdfkamskfmasklfmaksmfaskfmaksfaopsfmpaomsfpaf
      JWT_EXPIRES_IN: 90d
      BASE_URL: https://freepik.softvenceomega.com/bmr
      PORT: 5005
      MAIL_USER: arafatmannan2019@gmail.com
      MAIL_PASS: eurp zvyi gnoy enag
      ADMIN_EMAIL: 'arafatmannan9@gmail.com'
      ADMIN_PASS: 'admin1234'
      ADMIN_NAME: 'Arafat'
      REDIS_URL: redis://redis:6379
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 5005:5005
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: jesus_db
    restart: always
    # user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jesus_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis
    container_name: jesus_redis
    restart: always
    ports:
      - '6382:6379'

volumes:
  db-data: